"""Proposal generation: one call, one retry, then a deterministic offer.

The contract this module implements is the whole of the LLM failure story:

1. Build the prompt, call the model, parse the response.
2. If the response is not a well-formed proposal, tell the model exactly which
   field was wrong and call once more.
3. If that fails too — or if the model was never reachable — build a base-item-only
   proposal with no discount, chosen by `envelope.pick_base`.

One retry, not three. A model that returns malformed JSON twice in a row against
a declared response schema is not going to be talked into it on the third
attempt, and each attempt spends a share of a latency budget the buyer is waiting
on. The fallback is always available and always sells something, so the cost of
giving up early is a plainer offer rather than a failed request.

What this module deliberately does not do is check the proposal against the
catalog. An invented SKU, a discount past the cap, a quantity beyond stock — all
of them pass through here untouched and are refused by the policy kernel. That is
not laxity: the kernel's veto is the security property this system claims, and a
pre-filter here would mean the veto was never exercised and its failure would go
unnoticed until the day it mattered.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from decimal import Decimal
from typing import Any, Callable, Protocol, Sequence

import settings
from vyapaari import envelope as envelope_module
from vyapaari import prompt as prompt_module
from vyapaari.envelope import SellableSku
from vyapaari.gemini import GeminiClient, LLMUnavailable, is_configured
from vyapaari.prompt import ProposalRequest
from vyapaari.schema import RESPONSE_SCHEMA, Proposal, ProposedItem, SchemaError, parse

#: Where a proposal came from. Recorded in the ledger, so an audit can tell a
#: model's offer from the engine's without re-running anything.
SOURCE_LLM = "llm"
SOURCE_LLM_RETRY = "llm_retry"
SOURCE_FALLBACK = "fallback"

#: The `why` on a fallback line. Written here, by hand, because the fallback path
#: exists precisely for when no model is available to write one — and because
#: prose shown to a buyer should never be generated by string-formatting private
#: numbers into a sentence.
_FALLBACK_WHY = "Matches what you asked for and is in stock for immediate dispatch."

MAX_ATTEMPTS = 2


class Generator(Protocol):
    """The transport, narrowed to what this module uses.

    A protocol rather than the concrete client so a test can pass a two-line
    function — including one that returns deliberate garbage, which is how the
    retry and fallback paths are exercised without a network.
    """

    def __call__(
        self, *, system: str, user: str, response_schema: dict[str, Any]
    ) -> str: ...


@dataclass(frozen=True)
class ProposalOutcome:
    """What came back, and how much it cost to get it.

    `proposal` is None only when nothing in the catalog can satisfy the request —
    wrong category, over budget, out of stock. The caller must treat that as a
    refusal and not as an empty offer.
    """

    proposal: Proposal | None
    source: str
    attempts: int
    latency_ms: int
    errors: tuple[str, ...] = ()
    model: str | None = None

    @property
    def refused(self) -> bool:
        return self.proposal is None

    @property
    def from_model(self) -> bool:
        return self.source in (SOURCE_LLM, SOURCE_LLM_RETRY)

    def as_payload(self) -> dict[str, Any]:
        """The outcome as a ledger entry.

        The buyer's need is not in here and never will be: `/audit` is public, and
        a shopping request is the buyer's business. The proposal's own fields are
        SKUs, quantities, and percentages, all of which are already public facts
        about the catalog.
        """
        body: dict[str, Any] = {
            "source": self.source,
            "attempts": self.attempts,
            "latency_ms": self.latency_ms,
            "upsells": 0 if self.proposal is None else len(self.proposal.upsells),
        }
        if self.model:
            body["model"] = self.model
        if self.errors:
            body["schema_errors"] = list(self.errors)
        if self.proposal is not None:
            body["proposal"] = self.proposal.as_payload()
        return body


def _fallback_proposal(
    request: ProposalRequest, envelope: Sequence[SellableSku]
) -> Proposal | None:
    """A base item at list price, chosen by rule.

    No upsells and no discount. An upsell is a judgement call about what pairs
    with what, and a discount is money; neither is something to guess at when the
    component whose job it was has just failed twice.
    """
    by_sku = envelope_module.by_sku(envelope)
    chosen: SellableSku | None = None
    if request.base_sku and request.base_sku in by_sku:
        candidate = by_sku[request.base_sku]
        # Honour a named SKU only if it can actually be shipped. Naming an
        # out-of-stock SKU is a request the kernel would refuse anyway, and
        # substituting silently would sell the buyer something they did not ask
        # for.
        if candidate.available_qty >= request.qty:
            chosen = candidate
    if chosen is None:
        chosen = envelope_module.pick_base(
            envelope,
            query=request.need,
            category=request.category,
            budget_inr=request.budget_inr,
            qty=request.qty,
        )
    if chosen is None:
        return None
    return Proposal(
        base=ProposedItem(
            sku=chosen.sku,
            qty=request.qty,
            discount_pct=Decimal(0),
            why=_FALLBACK_WHY,
        ),
        upsells=(),
    )


def _default_generator() -> tuple[Generator | None, str | None, str | None]:
    """The live client, or a reason there isn't one."""
    if not is_configured():
        return None, None, "llm_not_configured"
    client = GeminiClient()
    return client.generate, client.model, None


def propose(
    request: ProposalRequest,
    envelope: Sequence[SellableSku],
    *,
    generate: Generator | None = None,
    model: str | None = None,
    clock: Callable[[], float] = time.perf_counter,
) -> ProposalOutcome:
    """Ask the model for a proposal; guarantee something usable comes back.

    `generate` is injectable so the retry and fallback paths can be tested without
    a network, and so a caller that already holds a warm client does not build a
    second one per request.
    """
    started = clock()
    errors: list[str] = []
    attempts = 0
    reason: str | None = None

    if generate is None:
        generate, resolved_model, reason = _default_generator()
        model = model or resolved_model
    if reason:
        errors.append(reason)

    def elapsed_ms() -> int:
        return int((clock() - started) * 1000)

    if generate is not None:
        repair_note: str | None = None
        while attempts < MAX_ATTEMPTS:
            attempts += 1
            try:
                built = prompt_module.build(
                    request, envelope, repair_note=repair_note
                )
                raw = generate(
                    system=built.system,
                    user=built.user,
                    response_schema=RESPONSE_SCHEMA,
                )
                proposal = parse(raw)
            except SchemaError as exc:
                # The one recoverable failure: the model answered, just not in the
                # agreed shape. Name the field so the retry is a correction rather
                # than another roll of the dice.
                errors.append(exc.as_repair_note())
                repair_note = exc.as_repair_note()
                continue
            except LLMUnavailable as exc:
                # No answer at all. A second attempt would wait out the same
                # timeout again, so stop here and let the fallback serve.
                errors.append(str(exc))
                break
            return ProposalOutcome(
                proposal=proposal,
                source=SOURCE_LLM if attempts == 1 else SOURCE_LLM_RETRY,
                attempts=attempts,
                latency_ms=elapsed_ms(),
                errors=tuple(errors),
                model=model,
            )

    return ProposalOutcome(
        proposal=_fallback_proposal(request, envelope),
        source=SOURCE_FALLBACK,
        attempts=attempts,
        latency_ms=elapsed_ms(),
        errors=tuple(errors),
        model=model,
    )


def budget_ms() -> int:
    """The offer path's latency budget, for callers that log against it."""
    return settings.LATENCY_BUDGETS_MS["offer"]
